---
name: box
ip: "192.168.50.4"
memory: 2048
cpus: 2

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/workspace/phalcon
      to: /home/vagrant/workspace/phalcon

sites:
    - map: phalcon.local
      to:  /home/vagrant/workspace/phalcon/public

databases:
    - phalcondb

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
