---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - import_tasks: include/initial.yml
    - import_tasks: include/certificates.yml
    - import_tasks: include/apt.yml
    - import_tasks: include/blackfire.yml
    - import_tasks: include/php-fpm.yml
    - import_tasks: include/nginx.yml
    - import_tasks: include/aliases.yml
    - import_tasks: include/dotfiles.yml
    - import_tasks: include/mysql.yml
    - import_tasks: include/postgresql.yml
    - import_tasks: include/mongo.yml
    - import_tasks: include/composer.yml
    - import_tasks: include/motd.yml
